services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatbot.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: BOT_NAME
        sync: false
      - key: GEMINI_API_KEY
        sunc: false
      - key: DB_NAME
        sync: false
      - key: DB_COLLECTION
        sync: false
      - key: DB_CLUSTER
        sync: false
